// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCteTa2vH7L1DxcwosVn9tX4iG2nV7Jr_Q',
    appId: '1:219214062860:web:3bcd1951ae13dd64e11529',
    messagingSenderId: '219214062860',
    projectId: 'bigbrain-fa1c3',
    authDomain: 'bigbrain-fa1c3.firebaseapp.com',
    databaseURL: 'https://bigbrain-fa1c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bigbrain-fa1c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbq4m6Pd3XGuXxPZ-3vHPjT4hJKr8yly0',
    appId: '1:219214062860:android:f6b825c56a05f271e11529',
    messagingSenderId: '219214062860',
    projectId: 'bigbrain-fa1c3',
    databaseURL: 'https://bigbrain-fa1c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bigbrain-fa1c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrmUFJfvdwOJUmHBzxskA8xFh2Nvl1gHs',
    appId: '1:219214062860:ios:6f14265c676d21dbe11529',
    messagingSenderId: '219214062860',
    projectId: 'bigbrain-fa1c3',
    databaseURL: 'https://bigbrain-fa1c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bigbrain-fa1c3.appspot.com',
    iosBundleId: 'com.example.bigbrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrmUFJfvdwOJUmHBzxskA8xFh2Nvl1gHs',
    appId: '1:219214062860:ios:c00c79112aa066c1e11529',
    messagingSenderId: '219214062860',
    projectId: 'bigbrain-fa1c3',
    databaseURL: 'https://bigbrain-fa1c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bigbrain-fa1c3.appspot.com',
    iosBundleId: 'com.example.bigbrain.RunnerTests',
  );
}
